Name:           perl-MouseX-Types-Path-Class
Version:        0.07
Release:        1%{?dist}
Summary:        Path::Class type library for Mouse
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MouseX-Types-Path-Class/
Source0:        http://www.cpan.org/authors/id/M/MA/MASAKI/MouseX-Types-Path-Class-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.1
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Mouse) >= 0.39
BuildRequires:  perl(MouseX::Getopt) >= 0.22
BuildRequires:  perl(MouseX::Types) >= 0.02
BuildRequires:  perl(Path::Class)
BuildRequires:  perl(Test::More) >= 0.94
BuildRequires:  perl(Test::UseAllModules)
Requires:       perl(Mouse) >= 0.39
Requires:       perl(MouseX::Getopt) >= 0.22
Requires:       perl(MouseX::Types) >= 0.02
Requires:       perl(Path::Class)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
MouseX::Types::Path::Class creates common Mouse types, coercions and option
specifications useful for dealing with Path::Class objects as Mouse
attributes.

%prep
%setup -q -n MouseX-Types-Path-Class-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 11 2013 David E. Wheeler <david.wheeler@iovation.com> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
