Name:           perl-Throwable
Version:        0.102080
Release:        1%{?dist}
Summary:        Role for classes that can be thrown
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Throwable/
Source0:        http://cpan.metacpan.org//authors/id/R/RJ/RJBS/Throwable-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Devel::StackTrace) >= 1.21
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose) >= 0.87
BuildRequires:  perl(Moose::Role) >= 0.87
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(Test::More)
Requires:       perl(Devel::StackTrace) >= 1.21
Requires:       perl(Moose) >= 0.87
Requires:       perl(Moose::Role) >= 0.87
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Throwable is a role for classes that are meant to be thrown as exceptions
to standard program flow. It is very simple and does only two things: saves
any previous value for $@ and calls die $self.

%prep
%setup -q -n Throwable-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 02 2012 David E. Wheeler <david.wheeler@iovation.com> 0.102080-1
- Specfile autogenerated by cpanspec 1.78.
