Name:           perl-MouseX-Getopt
Version:        0.34
Release:        1%{?dist}
Summary:        Mouse role for processing command line options
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MouseX-Getopt/
Source0:        http://www.cpan.org/authors/id/G/GF/GFUJI/MouseX-Getopt-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Getopt::Long::Descriptive) >= 0.091
BuildRequires:  perl(Mouse) >= 0.64
BuildRequires:  perl(Test::Exception) >= 0.21
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Warn) >= 0.21
Requires:       perl(Getopt::Long::Descriptive) >= 0.091
Requires:       perl(Mouse) >= 0.64
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is a role which provides an alternate constructor for creating objects
using parameters passed in from the command line.

%prep
%setup -q -n MouseX-Getopt-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog ChangeLog~ dist.ini dist.ini~ LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Jan 11 2013 David E. Wheeler <david.wheeler@iovation.com> 0.34-1
- Specfile autogenerated by cpanspec 1.78.
