Name:           perl-namespace-autoclean
Version:        0.19
Release:        1%{?dist}
Summary:        Keep imports out of your namespace
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/namespace-autoclean/
Source0:        http://cpan.metacpan.org/authors/id/E/ET/ETHER/namespace-autoclean-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(B::Hooks::EndOfScope) >= 0.12
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(namespace::clean) >= 0.20
BuildRequires:  perl(Sub::Identify)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Requires)
BuildRequires:  perl(version)
Requires:       perl(B::Hooks::EndOfScope) >= 0.12
Requires:       perl(namespace::clean) >= 0.20
Requires:       perl(Sub::Identify)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
When you import a function into a Perl package, it will naturally also be
available as a method.

%prep
%setup -q -n namespace-autoclean-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING dist.ini LICENSE META.json README README.md weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Aug 05 2014 David E. Wheeler <david.wheeler@iovation.com> 0.19-1
- Specfile autogenerated by cpanspec 1.78.
