Name:           perl-MooseX-ClassAttribute
Version:        0.26
Release:        1%{?dist}
Summary:        Declare class attributes Moose-style
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooseX-ClassAttribute/
Source0:        http://cpan.metacpan.org//authors/id/D/DR/DROLSKY/MooseX-ClassAttribute-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose) >= 1.23
BuildRequires:  perl(namespace::autoclean) >= 0.11
BuildRequires:  perl(namespace::clean) >= 0.20
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Requires) >= 0.05
Requires:       perl(Moose) >= 1.23
Requires:       perl(namespace::autoclean) >= 0.11
Requires:       perl(namespace::clean) >= 0.20
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module allows you to declare class attributes in exactly the same way
as object attributes, using class_has() instead of has().

%prep
%setup -q -n MooseX-ClassAttribute-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Sat Aug 04 2012 David E. Wheeler <david.wheeler@iovation.com> 0.26-1
- Specfile autogenerated by cpanspec 1.78.
