Name:           perl-Type-Tiny
Version:        0.046
Release:        1%{?dist}
Summary:        Tiny, yet Moo(se)-compatible type constraint
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Type-Tiny/
Source0:        http://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Type-Tiny-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006001
BuildRequires:  perl(B)
BuildRequires:  perl(B::Deparse)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Devel::LexAlias) >= 0.05
BuildRequires:  perl(Devel::StackTrace)
BuildRequires:  perl(Exporter::Tiny) >= 0.026
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Scalar::Util)  
BuildRequires:  perl(Sub::Name)
BuildRequires:  perl(Test::More) >= 0.96
BuildRequires:  perl(Text::Balanced)
BuildRequires:  perl(Type::Tie)
BuildRequires:  perl(Type::Tiny::XS) >= 0.003
BuildRequires:  perl(base)
BuildRequires:  perl(mro)
BuildRequires:  perl(overload)
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
Requires:       perl >= 0:5.006001
Requires:       perl(B)
Requires:       perl(B::Deparse)
Requires:       perl(Data::Dumper)
Requires:       perl(Devel::LexAlias) >= 0.05
Requires:       perl(Devel::StackTrace)
Requires:       perl(Exporter::Tiny) >= 0.026
Requires:       perl(ExtUtils::MakeMaker)
Requires:       perl(Scalar::Util)  
Requires:       perl(Sub::Name)
Requires:       perl(Test::More) >= 0.96
Requires:       perl(Text::Balanced)
Requires:       perl(Type::Tie)
Requires:       perl(Type::Tiny::XS) >= 0.003
Requires:       perl(base)
Requires:       perl(mro)
Requires:       perl(overload)
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
AutoReq: 0

%description
Type::Tiny is a tiny class for creating Moose-like type constraint objects
which are compatible with Moo, Moose and Mouse.

%prep
%setup -q -n Type-Tiny-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes CONTRIBUTING COPYRIGHT CREDITS dist.ini doap.ttl LICENSE META.json NEWS README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Aug 05 2014 David E. Wheeler <david.wheeler@iovation.com> 0.046-1
- Specfile autogenerated by cpanspec 1.78.
