Name:           perl-URI-Nested
Version:        0.10
Release:        1%{?dist}
Summary:        Perl module for nested URIs
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/URI-Nested/
Source0:        http://cpan.metacpan.org//authors/id/D/DW/DWHEELER/URI-Nested-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008001
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(URI) >= 1.40
Requires:       perl(URI) >= 1.40
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This class provides support for nested URIs, where the scheme is a prefix, and
the remainder of the URI is another URI. Examples include JDBC URIs and
database URIs.

%prep
%setup -q -n URI-Nested-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Fri Dec 20 2013 David E. Wheeler <david.wheeler@iovation.com> 0.10-1
- Specfile autogenerated by cpanspec 1.78.
